#!/usr/bin/env python3
"""
Generate Demo Excel Export
Creates a professional Excel file you can show to contractors
No frontend needed - just run this script
"""

import sys
import json
from pathlib import Path
from datetime import datetime

# Try to import openpyxl
try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("Installing openpyxl...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "openpyxl"])
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
    from openpyxl.utils import get_column_letter

# Add backend to path
sys.path.insert(0, str(Path(__file__).parent.parent / "painting-ai" / "backend"))

from demo_workflow import create_sample_project
from drywall_assembly_expansion import DrywallAssemblyExpander


def create_professional_excel(result, filename="Drywall_Estimate_Demo.xlsx"):
    """
    Create a professional Excel estimate that contractors can use
    This is what they'll get from your product
    """
    wb = Workbook()

    # Sheet 1: Summary
    summary_sheet = wb.active
    summary_sheet.title = "Summary"

    # Sheet 2: Detailed Line Items
    detail_sheet = wb.create_sheet("Detailed Estimate")

    # Create summary sheet
    create_summary_sheet(summary_sheet, result)

    # Create detail sheet
    create_detail_sheet(detail_sheet, result)

    # Save
    output_path = Path(__file__).parent / filename
    wb.save(output_path)
    print(f"\n✓ Excel file created: {output_path}")
    return output_path


def create_summary_sheet(ws, result):
    """Create summary sheet with project overview"""

    # Header
    ws['A1'] = "DRYWALL TAKEOFF ESTIMATE"
    ws['A1'].font = Font(size=18, bold=True, color="FFFFFF")
    ws['A1'].fill = PatternFill(start_color="1F4788", end_color="1F4788", fill_type="solid")
    ws['A1'].alignment = Alignment(horizontal="center")
    ws.merge_cells('A1:E1')

    # Project info
    row = 3
    ws[f'A{row}'] = "Project:"
    ws[f'B{row}'] = "Office Renovation - Sample"
    ws[f'A{row}'].font = Font(bold=True)

    row += 1
    ws[f'A{row}'] = "Date:"
    ws[f'B{row}'] = datetime.now().strftime("%B %d, %Y")
    ws[f'A{row}'].font = Font(bold=True)

    row += 1
    ws[f'A{row}'] = "Generated by:"
    ws[f'B{row}'] = "Drywall.ai (AI-Powered Takeoff)"
    ws[f'A{row}'].font = Font(bold=True)

    # Project metrics
    row += 2
    ws[f'A{row}'] = "PROJECT METRICS"
    ws[f'A{row}'].font = Font(size=14, bold=True)
    ws[f'A{row}'].fill = PatternFill(start_color="E7E6E6", end_color="E7E6E6", fill_type="solid")
    ws.merge_cells(f'A{row}:E{row}')

    summary = result["summary"]
    metrics = [
        ("Total Walls:", summary['total_walls']),
        ("Total Ceilings:", summary['total_ceilings']),
        ("Wall Square Feet:", f"{summary['net_wall_sqft']:,.0f} sqft"),
        ("Ceiling Square Feet:", f"{summary['ceiling_sqft']:,.0f} sqft"),
        ("Total Square Feet:", f"{summary['total_sqft']:,.0f} sqft"),
        ("Wall Linear Feet:", f"{summary['wall_linear_feet']:,.0f} LF"),
        ("Inside Corners:", summary['inside_corners']),
        ("Outside Corners:", summary['outside_corners']),
    ]

    for metric, value in metrics:
        row += 1
        ws[f'A{row}'] = metric
        ws[f'B{row}'] = value
        ws[f'A{row}'].font = Font(bold=True)

    # Cost breakdown
    row += 2
    ws[f'A{row}'] = "COST BREAKDOWN"
    ws[f'A{row}'].font = Font(size=14, bold=True)
    ws[f'A{row}'].fill = PatternFill(start_color="E7E6E6", end_color="E7E6E6", fill_type="solid")
    ws.merge_cells(f'A{row}:E{row}')

    costs = result["costs"]
    cost_items = [
        ("Material Cost:", costs['material_cost']),
        ("Labor Cost:", costs['labor_cost']),
        ("Subtotal:", costs['subtotal']),
        ("Overhead (15%):", costs['overhead']),
        ("Profit (20%):", costs['profit']),
    ]

    for item, amount in cost_items:
        row += 1
        ws[f'A{row}'] = item
        ws[f'B{row}'] = f"${amount:,.2f}"
        ws[f'A{row}'].font = Font(bold=True)

    row += 1
    ws[f'A{row}'] = "TOTAL:"
    ws[f'B{row}'] = f"${costs['total_cost']:,.2f}"
    ws[f'A{row}'].font = Font(size=14, bold=True)
    ws[f'B{row}'].font = Font(size=14, bold=True, color="FF0000")

    row += 1
    ws[f'A{row}'] = "Cost per sqft:"
    ws[f'B{row}'] = f"${costs['cost_per_sqft']:.2f}/sqft"
    ws[f'A{row}'].font = Font(bold=True)
    ws[f'B{row}'].font = Font(bold=True)

    # Column widths
    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 25


def create_detail_sheet(ws, result):
    """Create detailed line items sheet"""

    # Header
    ws['A1'] = "DETAILED ESTIMATE - LINE ITEMS"
    ws['A1'].font = Font(size=14, bold=True, color="FFFFFF")
    ws['A1'].fill = PatternFill(start_color="1F4788", end_color="1F4788", fill_type="solid")
    ws['A1'].alignment = Alignment(horizontal="center")
    ws.merge_cells('A1:H1')

    # Column headers
    headers = ["Item", "Division", "Category", "Description", "Specification", "Qty", "Unit", "Cost"]
    row = 3
    for col, header in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        cell.alignment = Alignment(horizontal="center")

    # Line items
    line_items = result["line_items"]
    current_division = None

    for item in line_items:
        row += 1

        # Division separator
        if item["division"] != current_division:
            current_division = item["division"]
            ws.merge_cells(f'A{row}:H{row}')
            cell = ws.cell(row=row, column=1, value=current_division)
            cell.font = Font(bold=True, size=12)
            cell.fill = PatternFill(start_color="E7E6E6", end_color="E7E6E6", fill_type="solid")
            row += 1

        # Item data
        ws.cell(row=row, column=1, value=item["item_number"])
        ws.cell(row=row, column=2, value=item["division"])
        ws.cell(row=row, column=3, value=item["category"])
        ws.cell(row=row, column=4, value=item["description"])
        ws.cell(row=row, column=5, value=item["specification"])
        ws.cell(row=row, column=6, value=item["quantity"])
        ws.cell(row=row, column=7, value=item["unit"])
        ws.cell(row=row, column=8, value=f"${item['total_cost']:,.2f}")

        # Number formatting
        ws.cell(row=row, column=6).number_format = '0.00'

        # Alternating row colors
        if row % 2 == 0:
            for col in range(1, 9):
                ws.cell(row=row, column=col).fill = PatternFill(
                    start_color="F2F2F2", end_color="F2F2F2", fill_type="solid"
                )

    # Totals row
    row += 2
    ws.cell(row=row, column=6, value="TOTAL:")
    ws.cell(row=row, column=6).font = Font(bold=True, size=12)
    ws.cell(row=row, column=8, value=f"${result['costs']['total_cost']:,.2f}")
    ws.cell(row=row, column=8).font = Font(bold=True, size=12, color="FF0000")

    # Column widths
    ws.column_dimensions['A'].width = 8
    ws.column_dimensions['B'].width = 25
    ws.column_dimensions['C'].width = 20
    ws.column_dimensions['D'].width = 40
    ws.column_dimensions['E'].width = 45
    ws.column_dimensions['F'].width = 10
    ws.column_dimensions['G'].width = 8
    ws.column_dimensions['H'].width = 12

    # Freeze header row
    ws.freeze_panes = 'A4'


def main():
    print("\n" + "📊" * 30)
    print(" " * 20 + "GENERATING DEMO EXCEL")
    print("📊" * 30)

    # Generate estimate data
    print("\n[1/2] Generating estimate data...")
    walls, ceilings = create_sample_project()
    expander = DrywallAssemblyExpander()
    result = expander.expand_project(
        walls=walls,
        ceilings=ceilings,
        finish_level=4,
        project_type="commercial"
    )
    print(f"      ✓ {result['line_item_count']} line items")
    print(f"      ✓ ${result['costs']['total_cost']:,.2f} total")

    # Create Excel file
    print("\n[2/2] Creating professional Excel file...")
    excel_path = create_professional_excel(result)

    # Done
    print("\n" + "="*80)
    print("  ✓ DEMO EXCEL READY")
    print("="*80)
    print(f"\nFile location: {excel_path}")
    print("\nWhat to do with this:")
    print("  1. Open the file - see what contractors will get")
    print("  2. Show this to potential customers in demos")
    print("  3. Send via email: 'This is what you'll get in 40 seconds'")
    print("  4. Use in your YC application (proof of value)")
    print("\nThis is your product demo without needing a frontend!\n")


if __name__ == "__main__":
    main()
